CREATE(joao:Pessoa:Pedreiro {nome: 'João', sexo: 'M', idade: 90})
CREATE(maria:Pessoa:Cozinheira {nome: 'Maria', sexo: 'F', idade: 85})
CREATE(rosana:Pessoa:Pintora {nome: 'Rosana', sexo: 'F', idade: 55})
CREATE(lucas:Pessoa:Engenheiro {nome: 'Lucas', sexo: 'M', idade: 40})
CREATE(gaby:Pessoa:Biomédica {nome: 'Gaby', sexo: 'F', idade: 34})
CREATE(fidelis:Pessoa:Estudante {nome: 'Fidelis', sexo: 'M', idade: 15})
CREATE(agnes:Pessoa:Estudante {nome: 'Agnes', sexo: 'F', idade: 14})
CREATE(lupi:Pet:Cachorro {nome: 'Lupi', sexo: 'M', idade: 4})
CREATE(silvio:Pessoa:Professor {nome: 'Silvio', sexo: 'M', idade: 60})
CREATE(roberta:Pessoa:Segurança {nome: 'Roberta', sexo: 'F', idade: 22})

CREATE(joao)-[:PAI_DE]->(rosana)
CREATE(joao)-[:PAI_DE]->(lucas)
CREATE(maria)-[:PAI_DE]->(rosana)
CREATE(maria)-[:PAI_DE]->(lucas)
CREATE(rosana)-[:PAI_DE]->(roberta)
CREATE(silvio)-[:PAI_DE]->(roberta)
CREATE(lucas)-[:PAI_DE]->(fidelis)
CREATE(lucas)-[:PAI_DE]->(agnes)
CREATE(gaby)-[:PAI_DE]->(fidelis)
CREATE(gaby)-[:PAI_DE]->(agnes)

CREATE(gaby)-[:DONO_DE]->(lupi)
CREATE(lucas)-[:DONO_DE]->(lupi)

CREATE(lucas)-[:IRMAO_DE]->(rosana)
CREATE(lucas)<-[:IRMAO_DE]-(rosana)
CREATE(fidelis)-[:IRMAO_DE]->(agnes)
CREATE(fidelis)<-[:IRMAO_DE]-(agnes)

CREATE(rosana)-[:NAMORADO_DE {desde:2015}]->(silvio)
CREATE(rosana)<-[:NAMORADO_DE {desde:2015}]-(silvio)

CREATE(joao)-[:ESPOSO_DE {desde:2010}]->(maria)
CREATE(joao)<-[:ESPOSO_DE {desde:2010}]-(maria)
CREATE(lucas)-[:ESPOSO_DE {desde:2012}]->(gaby)
CREATE(lucas)<-[:ESPOSO_DE {desde:2012}]-(gaby)